# SQLite datasource configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:${user.dir}/backend/db/flavour.db}
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080

